name: Test

on:
  workflow_dispatch:
  push:
    branches:
      - master
  pull_request:

jobs:
  test:
    runs-on: self-hosted
    defaults:
      run:
        shell: bash
        working-directory: packages/v3

    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v2
        with:
          node-version: '16'

      - name: Install V2 NPM Dependencies
        run: yarn install
        working-directory: packages/v2

      - name: Build V2
        run: yarn build
        working-directory: packages/v2

      - name: Install NPM Dependencies
        run: yarn install

      # temporary remove lint check from CI since solhint doesn't fully support Solidity 0.8.10
      # - name: Lint
      #   run: yarn lint

      - name: Test
        run: CI=1 yarn test

      - name: Test Migration
        run: CI=1 yarn test-migration
